server:
  port: 8400

#Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@JOE4VKINFCCPAYV3_high?TNS_ADMIN=/Users/jht56/OracleCloud/Wallet_JOE4VKINFCCPAYV3
    username: admin
    password: Rpdla56275627@
    
#     driver-class-name: oracle.jdbc.driver.OracleDriver
#     url: jdbc:oracle:thin:@localhost:1521/xe
#     username: personal_project
#     password: tiger
  
  #File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
    
  
  #View Resolver      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  
#Mybatis
mybatis:            #classpath는 resource이다.
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL